services:
  backend:
    image: cr.yandex/${REGISTRY_ID}/backend
    env_file:
      - .env-backend
    container_name: app-backend-1
    restart: always
    networks:
      - net

  frontend:
    image: cr.yandex/${REGISTRY_ID}/frontend
    container_name: app-frontend-1
    restart: always
    depends_on:
      - backend
    networks:
      - net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - frontend
      - backend
    networks:
      - net

networks:
  net:
    driver: bridge