worker-threads: 2
worker-fs-threads: 2
logger-level: debug

is-testing: true

server-port: 8080

metrics-port: 8081
metrics-path: /metrics
metrics-enabled: true

# change to URI of your mongo database
mongo-connection:  mongodb://admin1:admin123@rc1d-tntk53cdf8q2dklg.mdb.yandexcloud.net:27018/scenariousus?replicaSet=rs01&appName=mongosh+2.5.6
#mongo-connection: mongodb://admin:secret@mongodb:27017/scenariosus?authSource=admin